### ISSUE TITLE
QUESTION: Cors problem on ReactJS

### ISSUE THREAD

**Issue by IbrahimSerhat** [afulsamet/tc-id-verification#1]
its working on express as pretty good but i cant integrate to ReactJS, i got an following error:

`Access to fetch at 'https://tckimlik.nvi.gov.tr/Service/KPSPublic.asmx' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

@afulsamet , May you help me?

**Comment by afulsamet** [comment]
[soap](https://www.npmjs.com/package/soap) package works only on server side. 
So, you can only use `tc-id-verification` with Express or any http server framework.
If you want to call a soap service from the client, you can try [this example](https://stackoverflow.com/a/49153096/11588298) but you may still get an CORS error.
